version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:3001
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/frontend/node_modules
      - /app/apps/backend/node_modules
      - /app/packages/eslint-config-custom/node_modules
    depends_on:
      - backend
    networks:
      - dev-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: backend-dev
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/frontend/node_modules
      - /app/apps/backend/node_modules
      - /app/packages/eslint-config-custom/node_modules
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

